### ISSUE TITLE
What's the current state of completion? What's the license?

### ISSUE THREAD

**Issue by Hexstream** [robert-strandh/CLOS-MOP-HTML#1]
Hello,

A truly free, online version of the MOP specification would certainly be great!

I was wondering what the current state of completion of this project is, and what the license is. (I think public domain would be best...)

If you could add such information to the README and such, that would be great.

------------

(I'll almost certainly make my own HTML version of the MOP at some point, unless someone beats me to the punch in a manner I deem satisfactory, and I'm trying to evaluate if your project would be suitable as a base or if I should just do my own thing essentially from scratch as per my usual modus operandi...)

**Comment by phoe** [comment]
AFAIK, this is more or less complete now. See http://metamodular.com/CLOS-MOP/ for a deployed version.

**Comment by Hexstream** [comment]
Uh, cool. That should definitely be at least the project description's "website"...

(The license question remains... And maybe something more specific about what remains to do, if anything.)

**Comment by aarvid** [comment]
thanks for the link.  alu.org is down and probably gone. so its version is only available through the wayback machine.

**Comment by robert-strandh** [comment]
The website contains the complete contents of the freely available
chapters of the AMOP, plus some other material that I included myself,
such as the class graph of the MOP classes.

Contrary to previous HTML versions, this one respects the desire of
the authors of the AMOP, which is that any derived material be made
available according to the same conditions as the original
specification, i.e., "public domain".  In fact, this is the reason I
felt I had to create this project in the first place.  I was not
allowed to modify the existing HTML version, because the authors did
not respect this desire.

There might still be some errors or omissions, which is why I accept
patches.  Otherwise I consider it complete.  I strongly suspect that
phoe will at some point include some more modern-looking derivative in
his Common Lisp UltraSpec project.

I may work on a README some day.

**Comment by phoe** [comment]
> I strongly suspect that phoe will at some point include some more modern-looking derivative in his Common Lisp UltraSpec project.

I will, as soon as finish with the CL part.

**Comment by robert-strandh** [comment]
I added an explicit statement to the README file, saying that you have
the same rights to my version as you have to the original chapters of
the AMOP.

**Comment by Hexstream** [comment]
Great! Thanks for the clarifications, this is much more suitable for immediate consumption than I anticipated.

It would still be important to provide the http://metamodular.com/CLOS-MOP/ link as the website link in the project's description at https://github.com/robert-strandh/CLOS-MOP-HTML rather than just having it in this closed issue...

(A separate LICENSE file would also help usability.)
